baseURL = "https://nal.netlify.com/"
languageCode = "en-us"
title = "National Athletics League"
theme = "hyde"

[params]
 themeColor = "theme-base-NAL"
 logo = "images/NAL_Shield_White.png"
 description = "Athletics deserves more."
